CREATE TABLE IF NOT EXISTS todos (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL
);
